server:
  port: 8081

provider:
  baseUrl: http://localhost:8080

spring:
  cloud:
    gateway:
      routes:
        - id: showEmployee
          uri: ${provider.baseUrl}/employees/{id}
          predicates:
            - Path=/employees/{id}
        - id: listEmployees
          uri: ${provider.baseUrl}/employees
          predicates:
            - Path=/employees
        - id: webflux
          uri: lb://webflux
          predicates:
            - Path=/webflux/**
          filters:
            - RewritePath=/webflux/(?<path>.*), /$\{path}
      discovery:
        locator:
          enabled: true
  application:
    name: gateway


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"