server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: getEmployee
          uri: http://localhost:8080
          predicates:
            - Path=/employees/{id}
            - Method=GET
        - id: webflux
          uri: lb://webflux
          predicates:
            - Path=/webflux/**
          filters:
            - RewritePath=/webflux/(?<path>.*), /$\{path}
      discovery:
        locator:
          enabled: true
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
    name: gateway


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE


