server:
  port: 8989
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
        timeout:
          enabled: true
        circuitBreaker:
          enabled: true
          errorThresholdPercentage: 10
logging:
  level:
    com:
      netflix:
        hystrix: DEBUG
spring:
  application:
    name: netflix
  sleuth:
    messaging:
      kafka:
        enabled: false
