server:
  port: 8081
  servlet:
    context-path: /api

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/test"
    username: root
    password: 123456
    tomcat:
      validation-query: "SELECT 1"
      initial-size: 5
      max-active: 20
      max-wait: 1000
      min-idle: 10
      test-on-borrow: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true

